### ISSUE TITLE
회고 CRUD 구현

### ISSUE THREAD

**Issue by chanbyoung** [kwakmins/trekker-backend#12]
## ✨ 추가 기능
회고 및 프로젝트 종료 처리를 구현합니다.
## 📃 세부 사항
회고 속성에는 `소프트 스킬`, `하드 스킬`, `회고 내용`이 있고,
회고 작성/삭제에 따라 할일의 `완료 여부`를 업데이트 합니다.

추가로 프로젝트 종료시 완료 처리도 구현합니다.
## ☑️ TODO

- [x] 회고 및 스킬 엔티티 생성
- [x] 회고 CRUD 구현
- [x] 프로젝트 종료시 완료 처리 구현
