### ISSUE TITLE
온보딩 및 프로젝트 CRUD 구현

### ISSUE THREAD

**Issue by chanbyoung** [kwakmins/trekker-backend#9]
## ✨ 추가 기능
온보딩, 프로젝트 CRUD를 구현합니다.

## 📃 세부 사항
로그인 완료 시 온보딩을 완료 여부를 보내는 부분도 구현합니다.

프로젝트 기능 목록으로는 `생성`, `수정`, `읽기(상세)`, `읽기(목록)`, `삭제` 가 있습니다.
읽기(목록) 시  추가적으로 진행률을 계산하여 보냅니다.

프로젝트 종료시 보고서를 생성하는 부분은 추후에 개발할 예정입니다.

## ☑️ TODO

- [x] 온보딩 및 회원 관련 엔티티(직무) 추가 
- [x] 프로젝트 엔티티 추가
- [x] 온보딩 기능 구현
- [x] 프로젝트 CRUD 구현
